### ISSUE TITLE
it worked for 1 hour ...

### ISSUE THREAD

**Issue by jfadeuilhe** [marklagendijk/node-toogoodtogo-watcher#125]
Well, I have the impression that it only worked for 1 hour ...

A link with "authenticationIntervalInMS"?

Unless there is a quota of requests, should "pollingIntervalInMs" be reduced (currently 30s) ?

Thank you

**Comment by Slothoncrack** [comment]
Works for me for several hours now

**Comment by marklagendijk** [comment]
For me it has been working since the release of the new version.

> Unless there is a quota of requests, should "pollingIntervalInMs" be reduced (currently 30s) ?
No, this will only get you blocked.

In your other issue you said:
> I have several processes on my Synology for the family, perfect.
You shouldn't run several instances of this application in parallel. This will increase the number of requests, and get your IP blocked.

At some point I want to have a filtering feature where the favorite businesses can be filtered per Telegram chat.
That way it will be easier to share a single instance with multiple people.

**Comment by jfadeuilhe** [comment]
We waited a few days before making the connections again, and since then it has been working

For multiple connections it's to see, but it's family and my users are in Marseille, Avigon, Dijon and Paris so the monitored businesses are really not the same!
