### ISSUE TITLE
Question or feature idea

### ISSUE THREAD

**Issue by VeslavG** [marklagendijk/node-toogoodtogo-watcher#96]
Hi, 

if this is inappropriate, please delete it.
Thanks for the excellent product and helpful setup guidelines.

I have a question (or rather a feature idea) about automatic reservation of one (1) magic box in favorites.
My issue is even I'm using watcher with short refresh time -  I always late to book magic box from one particular supplier in particular timeframe.

Most probably someone is using automatic reservation (example here:  https://tgtg-alerts.com/en/auto, and  there are other similar services). I'm _always_ late for several seconds. Obviously, it is not a magic box of interest anymore, it is rather a "competition" to outsmart this person and make the reservation first (even I'm _not_ going to buy it, and will let him/her to purchase it later).

**Comment by marklagendijk** [comment]
It is true that it can turn into a competition.
Now doing auto-reservation is cheating, because then 'contenders' who don't use such automated tool can never win.

I don't think you're not getting the boxes because other people use an automated tool, but rather just because there are too many people interested.

I'm closing this, because it is a conscious decision not to implement automatic reservation.

**Comment by hoerbi1000** [comment]
Looks Like https://tgtg-alerts.com/ ist using the API for Reservation. So May the Feature of autoreservation should be rethink. :)

**Comment by KaKi87** [comment]
> doing auto-reservation is cheating, because then 'contenders' who don't use such automated tool can never win

As mentioned, there currently is a proprietary & paid platform which does this, and I'm pretty sure I witnessed it's use, because five times in a row, I was unable to reserve a bag while opening the app less than 15 seconds after receiving a notification.

Therefore, it doesn't seem unfair to me for us to have that feature as well.

Thanks
